get:
  summary: Get Chatroom Settings

  operationId: getChatroomSettings

  tags:
    - Chatroom

  security:
    - bearerAuth: []

  parameters:
    - $ref: "../../components/parameters/headers/versionCode.yaml"
    - $ref: "../../components/parameters/headers/platformCode.yaml"
    - $ref: "../../components/parameters/headers/platformType.yaml"
    - $ref: "../../components/parameters/headers/apiKey.yaml"
    - $ref: "../../components/parameters/headers/authToken.yaml"
    - $ref: "../../components/parameters/query/chatroomId.yaml"

  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object
                properties:
                  settings:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        is_selected:
                          type: boolean
                        title:
                          type: string
