version: 0.0
os: linux
files:
  - source: /scripts/build_auth.sh
    destination: /home/ubuntu/LikeMinds-Authentication/scripts
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: scripts/build_auth.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/start_auth.sh
      timeout: 300
      runas: ubuntu
