version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/LikeMinds-Authentication
hooks:
  ApplicationStart:
    - location: scripts/build_auth.sh
      timeout: 300
    - location: scripts/start_auth.sh
      timeout: 300
