apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "kettle"
  namespace: "app-deploy"
  labels:
    app: "kettle"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "kettle"
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: "kettle"
    spec:
      containers:
      - name: "likeminds-authentication-1"
        image: "asia.gcr.io/likeminds-nonprod-prj-24e1/github.com/nateshr/likeminds-authentication/kettle:80886b3"
        resources:
          requests:
            memory: "1000Mi"
            cpu: "500m"
          limits:
            memory: "1500Mi"
            cpu: "1000m"
  
---

apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "kettle"
  namespace: "app-deploy"
  labels:
    app: "kettle"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "kettle"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 75
