services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      # Name of the network created
      - local_auth
  auth:
    container_name: auth
    hostname: auth
    build:
      dockerfile: ./Dockerfile.kettle-local
    ports:
      - 8080:8080
    restart: always
    networks:
      # Name of the network created
      - local_auth
networks:
  local_auth:
    # Use a custom driver
    driver: bridge

