services:
  auth_redis:
    image: redis
    container_name: auth_redis
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - likeminds-network

  auth:
    container_name: auth
    build:
      dockerfile: ./Dockerfile.kettle-local
    ports:
      - 8080:8080
    restart: always
    networks:
      - likeminds-network
    depends_on:
      - auth_redis

networks:
  likeminds-network:
    external: true
