version: "1.0"
services:
  kettle:
    build: 
      context: "."
      args:
       - APPLICATION_ENV=BETA
    expose:
      - "8080"

  nginx:
    build: "./scripts/nginx"
    ports:
      - "80:80"
    depends_on:
      - "kettle"
