# syntax=docker/dockerfile:1

FROM golang:1.18-alpine
WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . ./

ADD ~/var/lib/jenkins/workspace/kettle-beta-test-env/.env ./.env

RUN go build -o ./kettle

CMD [ "./kettle" ]
