get:
  summary: Get User Channel Settings
  operationId: getUserChannelSettings
  tags:
    - Channel
  security:
    - bearerAuth: []
  parameters:
    - name: channel_id
      in: path
      description: ID of the channel
      required: true
      schema:
        type: integer
    - name: uuid
      in: path
      description: UUID of the user
      required: true
      schema:
        type: string
    - name: Authorization
      in: header
      description: JWT token
      schema:
        type: string
  requestBody:
    required: false
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              error_message:
                type: string
              data:
                type: object
                properties:
                  channel_settings:
                    type: array
                    items:
                      type: object
                      properties:
                        changed_by:
                          type: integer
                        chatroom_id:
                          type: integer
                        enabled:
                          type: boolean
                        setting_type:
                          type: string
                        user:
                          type: object
                          properties:
                            id:
                              type: integer
                            image_link:
                              type: string
                            is_guest:
                              type: boolean
                            name:
                              type: string
                            sdk_client_info:
                              type: object
                              properties:
                                community:
                                  type: integer
                                user:
                                  type: integer
                                user_unique_id:
                                  type: string
                            user_unique_id:
                              type: string



put:
  summary: Update User Channel Settings
  operationId: updateUserChannelSettings
  tags:
    - Channel
  security:
    - bearerAuth: []
  parameters:
    - name: channel_id
      in: path
      description: ID of the channel
      required: true
      schema:
        type: integer
    - name: uuid
      in: path
      description: UUID of the user
      required: true
      schema:
        type: string
    - name: Authorization
      in: header
      description: JWT token
      schema:
        type: string
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            channel_settings:
              type: array
              items:
                type: object
                properties:
                  setting_type:
                    type: string
                  enabled:
                    type: boolean
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              error_message:
                type: string
              data:
                type: object
                properties:
                  channel_settings:
                    type: array
                    items:
                      type: object
                      properties:
                        changed_by:
                          type: integer
                        chatroom_id:
                          type: integer
                        enabled:
                          type: boolean
                        setting_type:
                          type: string
                        user:
                          type: object
                          properties:
                            id:
                              type: integer
                            image_link:
                              type: string
                            is_guest:
                              type: boolean
                            name:
                              type: string
                            sdk_client_info:
                              type: object
                              properties:
                                community:
                                  type: integer
                                user:
                                  type: integer
                                user_unique_id:
                                  type: string
                            user_unique_id:
                              type: string
