get:
  summary: Get Chatroom Event Metadata

  operationId: getChatroomEventMeta

  tags:
    - Chatroom

  description: |
    This API fetches metadata for chatroom events of a community.

  security:
    - bearerAuth: []

  parameters:
    - $ref: "../../../components/parameters/headers/authToken.yaml"
    - $ref: "../../../components/parameters/headers/apiKey.yaml"
    - $ref: "../../../components/parameters/headers/platformCode.yaml"
    - $ref: "../../../components/parameters/headers/versionCode.yaml"
    - $ref: "../../../components/parameters/query/pastEvents.yaml"

  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              error_message:
                type: string
                nullable: true
              data:
                type: object
                properties:
                  chatroom:
                    type: object
                    nullable: true
                  chatrooms:
                    type: array
                    items:
                      type: object
