package user

const LoginEndPoint = "/api/user/login"
const BotEndpoint = "/api/user/bot"
const LogoutEndPoint = "/api/user/logout"
const MergeAccountEndPoint = "/api/merge_account"
const UserFetchEndPoint = "/api/user/fetch"
const WASubscriptionEndPoint = "/api/user/subscription/whatsapp"
const FetchUserAccessEndPoint = "/api/community_member/fetch_access"
const FetchMembersMetaEndPoint = "/api/community/fetch_members_meta"
const PushUserTokenEndPoint = "/api/push"
const FetchUserMetaEndPoint = "/api/fetch_user_meta"
const UserOTPEndpoint = "/api/user/otp"
const UserSocialLoginEndpoint = "/api/user/social/login"
const BlockUserEndpoint = "/api/user/%s/block"
const DashboardUserEndpoint = "/api/user/dashboard"

const ParamIngestCommunities = "ingest_your_communities"
const ParamAccessType = "access_type"
const ParamMemberIds = "member_ids"
const ParamMemberId = "member_id"
const ParamDeviceId = "device_id"
const ParamToken = "token"
const ResponseUser = "user"
const ResponseUserUniqueId = "user_unique_id"
const ResponseUserIsGuest = "is_guest"
const GuestLoginRoute = "route://guest_login"
const ConfigEndPoint = "/api/config"
const UserName = "name"
const UserEmail = "email"
const UserImageUrl = "image_url"
const UserOrganisationName = "organisation_name"
const UserMobileNo = "mobile_no"
const UserCountryCode = "country_code"
const UserLoginType = "type"
const ParamOTPMode = "otp_mode"
const ParamEmailID = "email_id"
const ParamOTP = "otp"
const ParamLoginType = "login_type"
const ParamSocialLoginToken = "token"
const ParamTokenType = "token_type"
const ParamUserUUID = "user_uuid"
const ParamBlockUserType = "block_user_type"
const ParamPage = "page"
const ParamPageSize = "page_size"
const ParamPlatformtype = "platform_type"
const ResponseUserExists = "existing_user"
const ParamMetaInfo = "meta_info"
const ParamUserData = "user_data"

const (
	VTM = "vtm"
	OTM = "otm"
)
