package chatroom

const CreateChatroomEndPoint = "/api/chatroom/create"
const EditChatroomEndPoint = "/api/chatroom/edit"
const FetchChatroomEndPoint = "/api/chatroom/fetch"
const FetchAllChatroomEndPoint = "/api/chatroom/fetch_all"
const GetTaggingListEndPoint = "/api/chatroom/get_tagging_list"
const PinChatroomEndPoint = "/api/chatroom/pin"
const ScheduleFollowEndPoint = "/api/chatroom/schedule_follow"
const FetchParticipantsMetaEndPoint = "/api/chatroom/fetch_participants_meta"
const FetchSecretParticipantsMetaEndPoint = "/api/chatroom/secret/fetch_participants_meta"
const AddParticipantsEndPoint = "/api/chatroom/add"
const AddSecretParticipantsEndPoint = "/api/chatroom/secret/add"
const FetchChatroomSettingsEndPoint = "/api/chatroom/fetch_settings"
const EnableMemberMessageEndPoint = "/api/chatroom/enable_member_message"
const AutoFollowMembersEndPoint = "/api/chatroom/auto_follow_for_all_members"
const DeleteChatroomEndPoint = "/api/chatroom_delete"
const ChatroomTypeEndPoint = "/api/chatroom/change_type"

const ParamChatroomId = "chatroom_id"
const ParamPage = "page"
const ParamIsSecret = "is_secret"
const ParamChatroomParticipants = "chatroom_participants"
const ResponseUser = "user"
const ResponseId = "id"
