get:
  summary: Get Community Settings
  operationId: getCommunitySettings
  tags:
    - Community
  security:
    - bearerAuth: []    
  parameters:
    - name: Authorization
      in: header
      required: true
      schema:
        type: string
        format: text
    - name: x-api-key
      in: header
      schema:
        type: string
        format: text
    - name: x-platform-code
      in: header
      schema:
        type: string
        format: text
    - name: x-version-code
      in: header
      schema:
        type: string
        format: text
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object
                properties:
                  community_settings:
                    type: array
                    items:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                        enabled_by:
                          type: integer
                        setting_sub_title:
                          type: string
                        setting_title:
                          type: string
                        setting_type:
                          type: string



put:
  summary: Update Community Settings
  operationId: updateCommunitySettings
  tags:
    - Community
  security:
    - bearerAuth: []
  parameters:
    - name: Authorization
      in: header
      required: true
      schema:
        type: string
        format: text
    - name: x-api-key
      in: header
      schema:
        type: string
        format: text
    - name: x-platform-type
      in: header
      schema:
        type: string
        format: text
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            community_settings:
              type: array
              items:
                type: object
                properties:
                  enabled:
                    type: boolean
                  enabled_by:
                    type: integer
                  setting_sub_title:
                    type: string
                  setting_title:
                    type: string
                  setting_type:
                    type: string
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
