get:
  summary: Get Community Settings
  operationId: getCommunitySettings
  tags:
    - Community
  security:
    - bearerAuth: []
  parameters:
    - $ref: "../../../components/parameters/headers/authToken.yaml"
    - $ref: "../../../components/parameters/headers/apiKey.yaml"
    - $ref: "../../../components/parameters/headers/platformCode.yaml"
    - $ref: "../../../components/parameters/headers/versionCode.yaml"
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object
                properties:
                  community_settings:
                    type: array
                    items:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                        enabled_by:
                          type: integer
                        setting_sub_title:
                          type: string
                        setting_title:
                          type: string
                        setting_type:
                          type: string



put:
  summary: Update Community Settings
  operationId: updateCommunitySettings
  tags:
    - Community
  security:
    - bearerAuth: []
  parameters:
    - $ref: "../../../components/parameters/headers/authToken.yaml"
    - $ref: "../../../components/parameters/headers/apiKey.yaml"
    - $ref: "../../../components/parameters/headers/platformType.yaml"
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../../../components/schemas/requests/community_settings.yaml"
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
