get:
  operationId: getCommunitySettings
  tags:
    - Community

  summary: Get Community Settings
  description: This API fetches Community Settings.

  security:
    - bearerAuth: []
  parameters:
    - $ref: "../../../components/parameters/headers/apiKey.yaml"
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: "../../../components/schemas/responses/community_settings_get.yaml"



put:
  operationId: updateCommunitySettings
  tags:
    - Community

  summary: Update Community Settings
  description: This API updates Community Settings.

  security:
    - bearerAuth: []
  parameters:
    - $ref: "../../../components/parameters/headers/apiKey.yaml"
    - $ref: "../../../components/parameters/headers/platformType.yaml"
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../../../components/schemas/requests/community_settings.yaml"
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: "../../../components/schemas/responses/community_settings_update.yaml"
