get:
  description: Get Community Member Home Meta

  operationId: getCommunityMemberHomeMeta

  tags:
    - Member

  security:
    - bearerAuth: []

  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: object
