get:
  summary: Get Community Member Home Meta

  operationId: getCommunityMemberHomeMeta

  tags:
    - Community

  security:
    - bearerAuth: []

  parameters:
    - name: Authorization
      in: header
      description: Authorization Token
      schema:
        type: string

  responses: {}
