type: object
properties:
  success:
    type: boolean
  error_message:
    type: string
  data:
    type: object
    properties:
      channel_settings:
        $ref: "./partials/channelSettings.yaml"
