type: object
properties:
  success:
    type: boolean
  data:
    type: object
    properties:
      community_configurations:
        type: array
        items:
          type: object
          properties:
            description:
              type: string
            type:
              type: string
            value:
              type: object
