type: object
properties:
  success:
    type: boolean
  error_message:
    type: string
    nullable: true
  data:
    type: object
    properties:
      settings:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            is_selected:
              type: boolean
            title:
              type: string
