openapi: 3.0.0
info:
  title: Kettle
  version: 2.12.1
  description: API Documention for LikeMinds Chat and Feed SDK
  contact: { email: support@likeminds.community }
servers:
  - url: https://auth.likeminds.community
tags:
  - name: Project
    description: APIs for Creating, Updating, Fetching and Deleting SDK Projects
  - name: Bot
    description: APIs for Fetching Bot details for a SDK Project
  - name: Login
    description: APIs to make User Login on SDK Dashboard, SDK Apps
  - name: Chatroom
    description: APIs for chatroom and related.
  - name: Feedroom
  - name: Poll
  - name: Community
  - name: Moderation
  - name: Conversation
  - name: Onboarding Screens
  - name: DM
  - name: Search
  - name: User
  - name: Feed
  - name: Feed - V1
    description: APIs related to Feed (Api Revamp v1)
  - name: Community feed
  - name: Helpers
  - name: Channel
  - name: Widget
  - name: Webhooks
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /sdk/project:
    $ref: "./api/sdk/project.yaml"

  /user/bot:
    $ref: "./api/user/bot.yaml"

  /user/login:
    $ref: "./api/user/login.yaml"
  /sdk/initiate:
    $ref: "./api/login/initiate.yaml" 
  /otp/generate:
    $ref: "./api/otp/generate.yaml"
  /otp/verify:
    $ref: "./api/otp/verify.yaml"
  /user/refresh:
    $ref: "./api/user/refresh.yaml"
  /user/logout:
    $ref: "./api/user/logout.yaml"
  /user/token:
    $ref: "./api/user/token.yaml"
  
  /chatroom:
    $ref: "./api/chatroom/chatroom.yaml"
  /chatroom/schedule_follow:
    $ref: "./api/chatroom/schedule_follow.yaml"
  /chatroom/participants:
    $ref: "./api/chatroom/participants.yaml"
  /chatroom/settings:
    $ref: "./api/chatroom/settings.yaml"
  /chatroom/type:
    $ref: "./api/chatroom/type.yaml"
  /chatroom/enable_member_message:
    $ref: "./api/chatroom/enable_member_message.yaml"
  /chatroom/pin:
    $ref: "./api/chatroom/pin.yaml"
  /chatroom/auto_follow_members:
    $ref: "./api/chatroom/auto_follow_members.yaml"
  /chatroom/tag:
    $ref: "./api/chatroom/tag.yaml"
  /chatroom/<chatroom_id>/tag:
    $ref: "./api/chatroom/chatroom_id/tag.yaml"
  /chatroom/files:
    $ref: "./api/chatroom/files.yaml"
  /chatroom/mine:
    $ref: "./api/chatroom/mine.yaml"
  /chatroom/seen:
    $ref: "./api/chatroom/seen.yaml"
  /chatroom/follow:
    $ref: "./api/chatroom/follow.yaml"
  /chatroom/mute:
    $ref: "./api/chatroom/mute.yaml"
  /chatroom/rename:
    $ref: "./api/chatroom/rename.yaml"
  /chatroom/share:
    $ref: "./api/chatroom/share.yaml"
  /chatroom/pending:
    $ref: "./api/chatroom/pending.yaml"
  /chatroom/sync:
    $ref: "./api/chatroom/sync.yaml"
  /chatroom/block:
    $ref: "./api/chatroom/block.yaml"
  /chatroom/search:
    $ref: "./api/chatroom/search.yaml"
  /chatroom/dm:
    $ref: "./api/chatroom/dm.yaml"
  /chatroom/dm/block:
    $ref: "./api/chatroom/dm/block.yaml"
  /chatroom/dm/limit:
    $ref: "./api/chatroom/dm/limit.yaml"
  /chatroom/dm/request:
    $ref: "./api/chatroom/dm/request.yaml"
  /chatroom/dm/create:
    $ref: "./api/chatroom/dm/create.yaml"
  /chatroom/cohort:
    $ref: "./api/chatroom/cohort.yaml"
  /chatroom/home:
    $ref: "./api/chatroom/home.yaml"
  /chatroom/mark_read:
    $ref: "./api/chatroom/mark_read.yaml"  
  /chatroom/event:
    $ref: "./api/chatroom/event.yaml"
  /chatroom/event/meta:
    $ref: "./api/chatroom/event/meta.yaml"
  /chatroom/event/link:
    $ref: "./api/chatroom/event/link.yaml"
  /chatroom/event/recordings:
    $ref: "./api/chatroom/event/recordings.yaml"
  /chatroom/event/instructors:
    $ref: "./api/chatroom/event/instructors.yaml"
  /chatroom/event/highlights:
    $ref: "./api/chatroom/event/highlights.yaml"
  /chatroom/event/testimonials:
    $ref: "./api/chatroom/event/testimonials.yaml"
  /chatroom/event/faq:
    $ref: "./api/chatroom/event/faq.yaml"
  /chatroom/event/recordings/meta:
    $ref: "./api/chatroom/event/recordings/meta.yaml"
  /chatroom/event/unseen_count:
    $ref: "./api/chatroom/event/unseen_count.yaml"

  /community/member:
    $ref: "./api/community/member.yaml"
  /community/report:
     $ref: "./api/community/report.yaml"
  /community/questions:
    $ref: "./api/community/questions.yaml"
  
  /moderation/rights:
    $ref: "./api/moderation/rights.yaml"

  /sdk/onboarding:
    $ref: "./api/sdk/onboarding.yaml"

  /feed/post:
    $ref: "./api/feed/v1/post/post.yaml"
  /feed/post/<post_id>:
    $ref: "./api/feed/v1/post/post_id.yaml"
  /feed/post/<post_id>/pin:
    $ref: "./api/feed/v1/post/pin.yaml"
  /feed/post/<post_id>/like:
    $ref: "./api/feed/v1/post/like.yaml"
  /feed/post/<post_id>/comment:
    $ref: "./api/feed/v1/post/comment/comment.yaml"
  /feed/post/<post_id>/comment/<comment_id>:
    $ref: "./api/feed/v1/post/comment/comment_id.yaml"
  /feed/post/<post_id>/save:
    $ref: "./api/feed/v1/post/save.yaml"
  /feed/post/<post_id>/comment/<comment_id>/comment:
    $ref: "./api/feed/v1/post/comment/comment_id/comment.yaml"
  /feed/post/<post_id>/comment/<comment_id>/like:
    $ref: "./api/feed/v1/post/comment/comment_id/like.yaml"
  /feed/user/<user_id>/save:
    $ref: "./api/feed/v1/user/save.yaml"
  /feed/user/<user_id>/post:
    $ref: "./api/feed/v1/user/post.yaml"
  /feed/user/<user_id>/activity:
    $ref: "./api/feed/v1/user/activity/activity.yaml"
  /feed/user/activity:
    $ref: "./api/feed/v1/user/activity.yaml"
  /feed/user/activity/<activity_id>/mark_read:
    $ref: "./api/feed/v1/user/activity/mark_read.yaml"
  /feed/user/activity/unread_count:
    $ref: "./api/feed/v1/user/activity/unread_count.yaml"
  /feed/universal:
    $ref: "./api/feed/v1/universal.yaml"
  /feed/group:
    $ref: "./api/feed/v1/group.yaml"
  /feed/topic:
    $ref: "./api/feed/v1/topic/topic.yaml"
  /feed/topic/<topic_id>:
    $ref: "./api/feed/v1/topic/topic_id.yaml"

  /poll/<poll_id>:
    $ref: "./api/poll/poll.yaml"
  /poll/<poll_id>/vote:
    $ref: "./api/poll/vote.yaml"

  /helper/url:
    $ref: "./api/helper/url.yaml"
  /helper/media/upload:
    $ref: "./api/helper/media_upload.yaml"
  /widget:
    $ref: "./api/widget.yaml"
  /webhooks:
    $ref: "./api/webhooks.yaml"
  # /search:
    # $ref: "./api/search/index.yaml"
    