package conversation

const FetchConversationEndPoint = "/api/conversation/fetch"
const CreateConversationEndPoint = "/api/conversation/create"
const AddReactionEndPoint = "/api/conversation/add_reaction"
const RemoveReactionEndPoint = "/api/conversation/remove_reaction"
const AddPollEndPoint = "/api/conversation/add_poll"
const SubmitPollEndPoint = "/api/conversation/submit_poll"
const PollUsersEndPoint = "/api/conversation/poll_users"
const SetTopicEndPoint = "/api/conversation/set_topic"
const EventAttendEndPoint = "/api/conversation/event/attend"
const EventAttendedEndPoint = "/api/conversation/event/attended"
const FetchEventUnseenCountEndPoint = "/api/conversation/event/fetch_unseen_count"
const UpdateLastSeenEventEndPoint = "/api/conversation/event/update_last_seen_event"
const EventFetchLinkEndPoint = "/api/conversation/event/fetch_link"
const EventFetchAllEndPoint = "/api/conversation/event/fetch_all"
const FetchUnreadPreviewsEndPoint = "/api/conversation/fetch_unread_previews"
const FetchPreviewUnreadMessagesCountEndPoint = "/api/conversation/fetch_preview_unread_messages_count"
const ConversationMetaEndPoint = "/api/conversation_meta"
const UnreadConversationNotificationEndPoint = "/api/unread_conversation_notification"
const DeleteConversationEndPoint = "/api/delete_conversation"
const EditConversationEndPoint = "/api/edit_conversation"
const SyncConversationEndPoint = "/api/sync_conversation"
const SyncConversationDiffEndPoint = "/api/sync_conversation_diff"

const ParamChatroomId = "chatroom_id"
const ParamConversationId = "conversation_id"
const ParamPollId = "poll_id"
const ParamPastEvents = "past_events"
const ParamAttendingStatus = "attending_status"
const ParamPage = "page"
const ParamPageSize = "page_size"
const ParamPaginatedBy = "paginated_by"
const ParamIsSynced = "is_synced"
const ParamMeta = "meta"
