get:
  summary: Get Community Configurations

  operationId: getCommunityConfigurations

  tags:
    - Community

  security:
    - bearerAuth: []

  parameters:
    - name: configuration_types
      in: query
      description: Configuration types to get
      schema:
        type: array
        items:
          type: string

  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/responses/community_configurations.yaml"
