package user

const LoginEndPoint = "/api/user/login"
const BotEndpoint = "/api/user/bot"
const LogoutEndPoint = "/api/user/logout"
const MergeAccountEndPoint = "/api/merge_account"
const UserFetchEndpoint = "/api/user/fetch"
const UserDMHomeEndpoint = "/api/user/fetch_dm_home"
const UserDMFeedEndpoint = "/api/user/fetch_dm_feed"
const UserSearchEndpoint = "/api/search/member_directory"
const UserCanDMEndpoint = "/api/community_member/can_dm"

const ParamIngestCommunities = "ingest_your_communities"
const ResponseUser = "user"
const ResponseUserUniqueId = "user_unique_id"
const ResponseUserIsGuest = "is_guest"
const GuestLoginRoute = "route://guest_login"
const ConfigEndPoint = "/api/config"
const UserName = "name"
const UserEmail = "email"
const UserImageUrl = "image_url"
const UserOrganisationName = "organisation_name"
const UserMobileNo = "mobile_no"
const UserCountryCode = "country_code"
const UserLoginType = "type"
const SearchParam = "search"
const SearchTypeParam = "search_type"
const MemberIDParam = "member_id"
const ChatroomIDParam = "chatroom_id"
const RequestFromParam = "req_from"
