package user

const LoginEndPoint = "/api/user/login"
const BotEndpoint = "/api/user/bot"
const LogoutEndPoint = "/api/user/logout"
const MergeAccountEndPoint = "/api/merge_account"
const UserFetchEndPoint = "/api/user/fetch"
const WASubscriptionEndPoint = "/api/user/subscription/whatsapp"
const FetchUserAccessEndPoint = "/api/community_member/fetch_access"
const FetchMembersMetaEndPoint = "/api/community/fetch_members_meta"

const ParamIngestCommunities = "ingest_your_communities"
const ParamAccessType = "access_type"
const ParamMemberIds = "member_ids"
const ResponseUser = "user"
const ResponseUserUniqueId = "user_unique_id"
const ResponseUserIsGuest = "is_guest"
const GuestLoginRoute = "route://guest_login"
const ConfigEndPoint = "/api/config"
const UserName = "name"
const UserEmail = "email"
const UserImageUrl = "image_url"
const UserOrganisationName = "organisation_name"
const UserMobileNo = "mobile_no"
const UserCountryCode = "country_code"
const UserLoginType = "type"
