get:
  summary: Feedroom Action

  operationId: feedroomAction

  tags:
    - Feedroom

  security:
    - bearerAuth: []

  parameters:
    - $ref: "../../components/parameters/headers/authToken.yaml"
    - $ref: "../../components/parameters/headers/apiKey.yaml"
    - name: feedroom_id
      in: query
      description: Feedroom ID
      schema:
        type: integer

  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object
                properties:
                  access_without_subscription:
                    type: boolean
                  can_access_secret_chatroom:
                    type: boolean
                  chatroom_actions:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                  participant_count:
                    type: integer
