get:
  summary: Fetch Chatroom Settings

  operationId: fetchChatroomSettings

  tags:
    - Feedroom

  security:
    - bearerAuth: []

  parameters:
    parameters:
    - $ref: "../../components/parameters/headers/authToken.yaml"
    - $ref: "../../components/parameters/headers/platformType.yaml"
    - $ref: "../../components/parameters/headers/apiKey.yaml"
    - $ref: "../../components/parameters/headers/platformCode.yaml"
    - $ref: "../../components/parameters/headers/versionCode.yaml"
    - name: feedroom_id
      in: query
      description: Chatroom ID
      required: true
      schema:
        type: integer

  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              error_message:
                type: string
                nullable: true
              data:
                type: object
                properties:
                  settings:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        is_selected:
                          type: boolean
                        title:
                          type: string
