get:
  summary: Fetch Chatroom Settings

  operationId: fetchChatroomSettings

  tags:
    - Feedroom

  security:
    - bearerAuth: []

  parameters:
    parameters:
    - $ref: "../../components/parameters/headers/authToken.yaml"
    - $ref: "../../components/parameters/headers/platformType.yaml"
    - $ref: "../../components/parameters/headers/apiKey.yaml"
    - $ref: "../../components/parameters/headers/platformCode.yaml"
    - $ref: "../../components/parameters/headers/versionCode.yaml"
    - $ref: "../../components/parameters/query/feedroomId.yaml"

  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/responses/feedroom_settings.yaml"
